name: SuperVanishV2
version: 2.0.0
api: [3.0.0-ALPHA11]
author: iCirgio, edited by VMPE Development Team
main: Vanish\Main

commands:
    supervanish: 
        permission: vanish.command
        description: "Vanishes the player who uses the command!"
        aliases: [sv]
        usage: "/supervanish or sv on/off/about"
